# Cloudflare Pages & D1 Database Configuration for GoooG
name = "gooog"
compatibility_date = "2024-09-01"
pages_build_output_dir = "dist"

# Cloudflare D1 SQL Database Binding
[[d1_databases]]
binding = "DB"
database_name = "gooog-db"
database_id = "e81a040b-7f38-4071-827e-9ede137cfa0e"
migrations_dir = "migrations"
